name: Build ESP32-S3 MicroPython Firmware

on:
  push:
    branches: [ "build-v1.23.0" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout MicroPython repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Enable deflate compression
      run: |
        echo '#define MICROPY_PY_DEFLATE_COMPRESS (1)' >> ports/esp32/mpconfigport.h

    - name: Build mpy-cross
      run: make -C mpy-cross -j2

    - name: Build ESP32-S3 firmware
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.4
        target: esp32s3
        path: ports/esp32
        command: |
          make submodules
          make BOARD=ESP32_GENERIC_S3

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: micropython-firmware
        path: ports/esp32/build-ESP32_GENERIC_S3/firmware.bin
