name: Build Custom ESP32-S3 MicroPython
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Prepare ESP-IDF v4.4
        run: |
          git clone -b v4.4 --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
          cd ~/esp-idf
          export IDF_GITHUB_ASSETS="dl.espressif.cn/github_assets"
          export PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
          ./install.sh esp32s3

      - name: Compile MicroPython
        run: |
          source ~/esp-idf/export.sh
          cd ports/esp32
          make BOARD=ESP32_GENERIC_S3 GENERATE_CERTS=0

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          path: ports/esp32/build/firmware.bin
          name: esp32s3-frozen-firmware
