name: ESP32-S3 自定义固件编译
on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MicroPython source
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Download ESP-IDF v4.4 official github
        run: |
          git clone --depth 1 -b v4.4 https://github.com/espressif/esp-idf.git ~/esp-idf
          cd ~/esp-idf
          # 工具链、资源全部走乐鑫国内服务器下载
          export IDF_GITHUB_ASSETS="dl.espressif.cn/github_assets"
          export PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
          ./install.sh esp32s3

      - name: Build ESP32-S3 firmware
        run: |
          source ~/esp-idf/export.sh
          cd ports/esp32
          EXTRA_CFLAGS="-Wno-error" make BOARD=ESP32_GENERIC_S3 GENERATE_CERTS=0 -j2

      - name: Upload compiled firmware
        uses: actions/upload-artifact@v4
        with:
          path: ports/esp32/build/firmware.bin
          name: esp32s3_frozen_firmware
